resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/johnmcollier/application-service/config/default?ref=fce594656f142efa0dcb29bd7da6e47d52abfde6
  - .tekton/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/application-service
    newName: quay.io/jcollier/application-service
    newTag: commitid
configMapGenerator:
  - literals:
      - GITHUB_ORG=hacbs-release-tests
    name: github-config
    behavior: replace
namespace: application-service
patches:
  - ./manager_resources_patch.yaml
