---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/scoheb/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-preview-release-service-config-by-env
