---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/scoheb/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-update-tenants-config-2
