apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/release-service/config/default?ref=116168adc7066139a1d0e22ffe04fb35faca36ce

images:
  - name: quay.io/redhat-appstudio/release-service
    newName: quay.io/redhat-appstudio/release-service
    newTag: 116168adc7066139a1d0e22ffe04fb35faca36ce

namespace: release-service
