apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/scoheb/release-service/config/default?ref=a22c085375eaeb32a38f3be0d1f57f408635a1ce
images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/scoheb/release-service
    newTag: volumetypes
namespace: release-service
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: sealights-token-patch.yaml
