apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/konflux-ci/release-service/config/default?ref=ad6af30b398fb2504c5d86cff19ed8c8036b35e3
images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/scoheb/release-service
    newTag: 140604a
namespace: release-service
