apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-permissions.yaml
  - https://github.com/metlos/service-provider-integration-operator/config/openshift?ref=79c96873a625c5a0f163666733eae128c2aa0c03

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: 02c2b7042a1b8cfff1fc489a964cc3142bcefcbe
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    newTag: 02c2b7042a1b8cfff1fc489a964cc3142bcefcbe

namespace: spi-system


patches:
  - target:
      kind: Deployment
      name: spi-controller-manager
    path: operator-limits-patch.json
patchesStrategicMerge:
  - delete-shared-configuration-file.yaml
