resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- release-pipeline-resources-clusterrole.yaml
- release-team.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: release-service
